apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  type: NodePort
  selector:
    app: python   
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 5000  
      nodePort: 30080 
